blueprint:
  name: Styrbar Remote Control (Custom Dim & Color)
  description: Control IKEA Styrbar. Off button dims instead of turning off. Arrows change color warmth.
  domain: automation
  input:
    mqtt_device:
      name: Styrbar Remote Control
      selector:
        device: {}
    light_entity:
      name: Light Entity
      selector:
        target:
          entity:
            domain: light
    brightness_step:
      name: Brightness Step
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    color_step:
      name: Color Temperature Step
      default: 500
      selector:
        number:
          min: 100
          max: 2000
          unit_of_measurement: "K"

mode: restart

trigger:
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "on"
    id: light_on
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "off"
    id: light_dim_only
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_down
    id: dim_down
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_up
    id: dim_up
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_left_click
    id: color_warmer
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_right_click
    id: color_cooler

action:
  - choose:
      # ON BUTTON: Full Brightness
      - conditions: [{condition: trigger, id: light_on}]
        sequence:
          - action: light.turn_on
            target: !input light_entity
            data:
              brightness_pct: 100

      # OFF BUTTON: Set to 10% instead of Off
      - conditions: [{condition: trigger, id: light_dim_only}]
        sequence:
          - action: light.turn_on
            target: !input light_entity
            data:
              brightness_pct: 10

      # BRIGHTNESS UP (HOLD)
      - conditions: [{condition: trigger, id: dim_up}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_up}]
              sequence:
                - action: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: !input brightness_step
                - delay: {milliseconds: 300}

      # BRIGHTNESS DOWN (HOLD)
      - conditions: [{condition: trigger, id: dim_down}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_down}]
              sequence:
                - action: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: -10
                - delay: {milliseconds: 300}

      # LEFT ARROW: Warmer (Lower Kelvin)
      - conditions: [{condition: trigger, id: color_warmer}]
        sequence:
          - action: light.turn_on
            target: !input light_entity
            data:
              color_temp_kelvin: "{{ (state_attr(device_entities(device_id( 'mqtt_device' ))[0], 'color_temp_kelvin') | default(3000, true)) - 500 }}"

      # RIGHT ARROW: Cooler (Higher Kelvin)
      - conditions: [{condition: trigger, id: color_cooler}]
        sequence:
          - action: light.turn_on
            target: !input light_entity
            data:
              color_temp_kelvin: "{{ (state_attr(device_entities(device_id( 'mqtt_device' ))[0], 'color_temp_kelvin') | default(3000, true)) + 500 }}"
