blueprint:
  name: Styrbar (Smooth Dim & Fixed Color)
  description: Fixes the brightness decrease issue and includes color temperature.
  domain: automation
  input:
    mqtt_device:
      name: Styrbar Remote Control
      selector:
        device: {}
    light_entity:
      name: Light Entity
      selector:
        target:
          entity:
            domain: light
    brightness_step:
      name: Brightness Step
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

variables:
  # This converts the input to a variable so the math works every time
  step_value: !input brightness_step
  target_light: !input light_entity

mode: restart

trigger:
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "on"
    id: light_on
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "off"
    id: light_dim_only
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_down
    id: dim_down
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_up
    id: dim_up
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_left_click
    id: color_warmer
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_right_click
    id: color_cooler

action:
  - choose:
      # ON: 100%
      - conditions: [{condition: trigger, id: light_on}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              brightness_pct: 100

      # OFF: 10%
      - conditions: [{condition: trigger, id: light_dim_only}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              brightness_pct: 10

      # BRIGHTNESS UP (HOLD)
      - conditions: [{condition: trigger, id: dim_up}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_up}]
              sequence:
                - service: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: "{{ step_value | int }}"
                - delay: {milliseconds: 300}

      # BRIGHTNESS DOWN (HOLD) - FIXED MATH
      - conditions: [{condition: trigger, id: dim_down}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_down}]
              sequence:
                - service: light.turn_on
                  target: !input light_entity
                  data:
                    # We multiply by -1 to ensure it's a negative decrease
                    brightness_step_pct: "{{ (step_value | int) * -1 }}"
                - delay: {milliseconds: 300}

      # COLOR WARMER
      - conditions: [{condition: trigger, id: color_warmer}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              color_temp_kelvin: >
                {% set entity = target_light.entity_id if target_light.entity_id is string else target_light.entity_id[0] %}
                {{ (state_attr(entity, 'color_temp_kelvin') | default(3000, true)) - 500 }}

      # COLOR COOLER
      - conditions: [{condition: trigger, id: color_cooler}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              color_temp_kelvin: >
                {% set entity = target_light.entity_id if target_light.entity_id is string else target_light.entity_id[0] %}
                {{ (state_attr(entity, 'color_temp_kelvin') | default(3000, true)) + 500 }}
