blueprint:
  name: Styrbar (Smooth Dim, Color & Response Speed)
  description: Adds transition time and stop-on-release for smooth control.
  domain: automation
  input:
    mqtt_device:
      name: Styrbar Remote Control
      selector:
        device: { integration: mqtt }
    light_entity:
      name: Light Entity
      selector:
        target:
          entity:
            domain: light
    brightness_step:
      name: Brightness Step
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"
    transition_time:
      name: Response Time (Transition)
      description: How many seconds the light takes to reach the next level.
      default: 0.5
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
          unit_of_measurement: "s"

variables:
  step_value: !input brightness_step
  trans_time: !input transition_time
  target_light: !input light_entity

mode: restart

trigger:
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "on"
    id: light_on
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "off"
    id: light_dim_only
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_up
    id: dim_up
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_down
    id: dim_down
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_stop
    id: stop_dimming
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_left_click
    id: color_warmer
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_right_click
    id: color_cooler

action:
  - choose:
      # ON/OFF logic remains the same
      - conditions: [{condition: trigger, id: light_on}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data: { brightness_pct: 100, transition: "{{ trans_time }}" }

      - conditions: [{condition: trigger, id: light_dim_only}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data: { brightness_pct: 10, transition: "{{ trans_time }}" }

      # BRIGHTNESS UP (With Transition)
      - conditions: [{condition: trigger, id: dim_up}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_up}]
              sequence:
                - service: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: "{{ step_value | int }}"
                    transition: "{{ trans_time }}"
                - delay: { milliseconds: 400 }

      # BRIGHTNESS DOWN (With Transition)
      - conditions: [{condition: trigger, id: dim_down}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_down}]
              sequence:
                - service: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: "{{ (step_value | int) * -1 }}"
                    transition: "{{ trans_time }}"
                - delay: { milliseconds: 400 }

      # STOP ACTION (Ends the repeat loop)
      - conditions: [{condition: trigger, id: stop_dimming}]
        sequence:
          - stop: "Button released"

      # COLOR logic (Transition makes this feel much smoother)
      - conditions: [{condition: trigger, id: color_warmer}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              transition: "{{ trans_time }}"
              color_temp_kelvin: >
                {% set entity = target_light.entity_id if target_light.entity_id is string else target_light.entity_id[0] %}
                {{ (state_attr(entity, 'color_temp_kelvin') | default(3000, true)) - 500 }}

      - conditions: [{condition: trigger, id: color_cooler}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              transition: "{{ trans_time }}"
              color_temp_kelvin: >
                {% set entity = target_light.entity_id if target_light.entity_id is string else target_light.entity_id[0] %}
                {{ (state_attr(entity, 'color_temp_kelvin') | default(3000, true)) + 500 }}
