blueprint:
  name: Styrbar Remote Control for Lights (Flexible)
  description: Control IKEA Styrbar remote. Device selection is unrestricted.
  domain: automation
  input:
    mqtt_device:
      name: Styrbar Remote Control
      description: Select your Styrbar Remote from the list.
      selector:
        device: {}
    light_entity:
      name: Light Entity
      description: The light to control.
      selector:
        target:
          entity:
            domain: light
    brightness_step:
      name: Brightness Step
      default: 5
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
    delay_ms:
      name: Delay (ms) Between Steps
      default: 300
      selector:
        number:
          min: 100
          max: 2000
          step: 100
          unit_of_measurement: "ms"
    transition_seconds:
      name: Transition Time
      default: 1
      selector:
        number:
          min: 0.1
          max: 10
          step: 0.1
          unit_of_measurement: "s"

mode: restart

trigger:
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "on"
    id: light_on
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "off"
    id: light_off
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_down
    id: dim_down
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_up
    id: dim_up
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_stop
    id: dim_stop
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_left_click
    id: color_left
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_right_click
    id: color_right

action:
  - choose:
      - conditions: [{condition: trigger, id: light_on}]
        sequence:
          - action: light.turn_on
            target: !input light_entity
      - conditions: [{condition: trigger, id: light_off}]
        sequence:
          - action: light.turn_off
            target: !input light_entity
      - conditions: [{condition: trigger, id: dim_up}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_up}]
              sequence:
                - action: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: !input brightness_step
                    transition: !input transition_seconds
                - delay: {milliseconds: !input delay_ms}
      - conditions: [{condition: trigger, id: dim_down}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_down}]
              sequence:
                - action: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: -{{ states(brightness_step) | int(5) }}
                    transition: !input transition_seconds
                - delay: {milliseconds: !input delay_ms}
