blueprint:
  name: Styrbar Remote (Smooth Dim & Color Fix)
  description: Controlled dimming speed and fixed color temperature logic.
  domain: automation
  input:
    mqtt_device:
      name: Styrbar Remote Control
      selector:
        device: {}
    light_entity:
      name: Light Entity
      selector:
        target:
          entity:
            domain: light
    brightness_step:
      name: Brightness Step
      default: 5
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"
    dim_speed:
      name: Dimming Delay
      description: Increase this to slow down the dimming (ms).
      default: 500
      selector:
        number:
          min: 100
          max: 1000
          step: 50
          unit_of_measurement: "ms"

mode: restart

# This helper helps the template find the right light ID
variables:
  target_light: !input light_entity

trigger:
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "on"
    id: light_on
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: "off"
    id: light_dim_only
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_down
    id: dim_down
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: brightness_move_up
    id: dim_up
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_left_click
    id: color_warmer
  - platform: device
    device_id: !input mqtt_device
    domain: mqtt
    type: action
    subtype: arrow_right_click
    id: color_cooler

action:
  - choose:
      # ON: Full
      - conditions: [{condition: trigger, id: light_on}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              brightness_pct: 100

      # OFF: Dim to 10%
      - conditions: [{condition: trigger, id: light_dim_only}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              brightness_pct: 10

      # BRIGHTNESS UP (HOLD)
      - conditions: [{condition: trigger, id: dim_up}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_up}]
              sequence:
                - service: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: !input brightness_step
                    transition: 0.4
                - delay: {milliseconds: !input dim_speed}

      # BRIGHTNESS DOWN (HOLD)
      - conditions: [{condition: trigger, id: dim_down}]
        sequence:
          - repeat:
              while: [{condition: trigger, id: dim_down}]
              sequence:
                - service: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: -{{ states(brightness_step) | int(5) }}
                    transition: 0.4
                - delay: {milliseconds: !input dim_speed}

      # COLOR WARMER
      - conditions: [{condition: trigger, id: color_warmer}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              # This finds the current color of the BULB directly
              color_temp_kelvin: >
                {% set entity = target_light.entity_id if target_light.entity_id is string else target_light.entity_id[0] %}
                {{ (state_attr(entity, 'color_temp_kelvin') | default(3000, true)) - 400 }}

      # COLOR COOLER
      - conditions: [{condition: trigger, id: color_cooler}]
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              color_temp_kelvin: >
                {% set entity = target_light.entity_id if target_light.entity_id is string else target_light.entity_id[0] %}
                {{ (state_attr(entity, 'color_temp_kelvin') | default(3000, true)) + 400 }}
